# api/shared/contants/contants.py

NAMES_MAX_LENGTH = 80
CLOUDINARY_PUBLIC_ID_MAX_LENGTH = 100
CLOUDINARY_RESOURCE_TYPE_MAX_LENGTH = 100
URLS_MAX_LENGTH = 254

IMAGE_DELETED = "La imagen fué eliminada"
IMAGE_NOT_FOUND = "La imagen no fué encontrada"

# Colors
AZUL_CIELO = "#3b82f6"
VERDE_ESMERALDA = "#10b981"


# Models

VETERINARY_CENTER_MODEL = "Veterinary_Center"
VET_CLINICAL_FOCUS_MODEL = "Vet_Clinical_Focus"
VET_CENTER_PERSONNEL_MODEL = "Vet_Center_Personnel"
CONTACT_MODEL = "Contact"
GLOBAL_SPECIES_MODEL = "Global_Species"
GLOBAL_BREED_MODEL = "Global_Breed"
SPECIES_IN_CENTER_MODEL = "Species_In_Center"
BREED_IN_CENTER_MODEL = "Breed_In_Center"
PET_MODEL = "Pet"
PET_DISEASE_CASE_MODEL = "Pet_Disease_Case"
PET_PROBLEM_CASE_MODEL = "Pet_Problem_Case"
DISEASE_GROUP_MODEL = "Disease_Group"
PROBLEM_GROUP_MODEL = "Problem_Group"
PROBLEM_CATALOG_MODEL = "Problem_Catalog"
DISEASE_CATALOG_MODEL = "Disease_Catalog"
SELF = "self"
CONSULTATION_MODEL = "Consultation"
CONSULTATION_TYPE_MODEL = "Consultation_Type"
MEDICATION_MODEL = "Medication"
CLINICAL_EVENT_MODEL = "Clinical_Event"
FOLLOW_UP_CATEGORY_MODEL = "Follow_Up_Category"
SOAP_TEMPLATE_MODEL = "SOAP_Template"
PROCEDURE_TYPE_MODEL = "Procedure_Type"
VACCINE_TYPE_MODEL = "Vaccine_Type"
CLINICAL_FOCUS_FOR_SOAP_TEMPLATE_MODEL = "Clinical_Focus_For_SOAP_Template"
IMAGE_MODEL = "Image"
HOSPITALIZATION_MODEL = "Hospitalization"
HOSPITALIZATION_UNIT_MODEL = "Hospitalization_Unit"
CAMPAIGN_MODEL = "Campaign"


# Related names

CLINICAL_FOCUSES_VETERINARIANS_RN = "clinical_focuses_veterinarians"
PERSONNEL_LOGIN_SESSIONS_RN = "personnel_login_sessions"
CENTER_IMAGES_RN = "center_images"
CENTER_SPECIES = "center_species"
SPECIES_BREEDS = "species_breeds"
CENTER_SPECIES_IN_CENTER_RN = "center_species_in_center"
SPECIES_IN_CENTER_BREEDS_IN_CENTER_RN = "species_in_center_breeds_in_center"
SPECIES_GLOBAL_BREEDS_RN = "species_global_breeds"
GLOBAL_SPECIES_SPECIES_IN_CENTER_RN = "global_species_species_in_center"
GLOBAL_BREED_BREEDS_IN_CENTER_RN = "global_breed_breeds_in_center"
SPECIES_PETS_RN = "species_pets"
LAST_ATTENDING_VET_PETS_RN = "last_attending_vet_pets"
CONTACTS_PETS_RN = "contacts_pets"
MERGED_PET_PETS_RN = "merged_pet_pets"
MERGED_BY_PETS_RN = "merged_by_pets"
OWNER_OWNED_PETS = "owner_owned_pets"
BROUGHT_BY_BROUGHT_PETS = "brought_by_brought_pets"
SPECIES_DISEASE_GROUPS_RN = "species_disease_groups"
CENTER_DISEASE_GROUPS_RN = "center_disease_groups"
CENTER_DISEASE_CATALOGS_RN = "center_disease_catalogs"
DISEASE_GROUP_CATALOGS_RN = "group_disease_catalogs"
PET_DISEASE_CASES_RN = "pet_disease_cases"
DISEASE_CATALOG_CASES_RN = "disease_catalog_cases"
RELAPSED_DISEASE_CASES_RN = "relapsed_disease_cases"
INITIAL_CONSULTATION_DISEASE_CASES_RN = "initial_consultation_disease_cases"
CENTER_DISEASE_CASES_RN = "center_disease_cases"
RESOLVED_BY_DISEASE_CASES_RN = "resolved_by_disease_cases"
CREATED_BY_DISEASE_CASES_RN = "created_by_disease_cases"
DISEASE_CASE_EVENTS_RN = "disease_case_events"
CONSULTATION_DISEASE_EVENTS_RN = "consultation_disease_events"
CENTER_DISEASE_EVENTS_RN = "center_disease_events"
UPDATED_BY_DISEASE_EVENTS_RN = "updated_by_disease_events"
PET_CLINICAL_COMORBIDITIES_RN = "pet_clinical_comorbidities"
DISEASE_CASES_CLINICAL_COMORBIDITIES_rn = "disease_cases_clinical_comorbidities"
SPECIES_PROBLEM_GROUPS_RN = "species_problem_groups"
CENTER_PROBLEM_GROUPS_RN = "center_problem_groups"
CENTER_PROBLEM_CATALOGS_RN = "center_problem_catalogs"
SPECIES_PROBLEM_CATALOGS_RN = "species_problem_catalogs"
PROBLEM_GROUP_CATALOGS_RN = "group_problem_catalogs"
PET_PROBLEM_CASES_RN = "pet_problem_cases"
PROBLEM_CATALOG_PROBLEM_CASES_RN = "problem_catalog_problem_cases"
CENTER_PROBLEM_CASES_RN = "center_problem_cases"
RELAPSED_PROBLEM_CASES_RN = "relapsed_problem_cases"
CREATED_BY_PROBLEM_CASES_RN = "created_by_problem_cases"
PROBLEM_CASE_PROBLEM_EVENTS_RN = "problem_case_problem_events"
CONSULTATION_PROBLEM_EVENTS_RN = "consultation_problem_events"
CENTER_PROBLEM_EVENTS_RN = "center_problem_events"
UPDATED_BY_PROBLEM_EVENTS_RN = "updated_by_problem_events"
CENTER_CONSULTATION_TYPES_RN = "center_consultation_types"
PET_CONSULTATIONS_RN = "pet_consultations"
CENTER_CONSULTATIONS_RN = "center_consultations"
CENTER_PROCEDURE_TYPES_RN = "center_procedure_types"
SPECIES_VACCINE_TYPES_RN = "species_vaccine_types"
CENTER_VACCINE_TYPES_RN = "center_vaccine_types"
CENTER_MEDICATIONS_RN = "center_medications"
PET_PRESCRIPTION_RECORDS = "pet_prescription_records"
MEDICATION_PRESCRIPTION_RECORDS = "medication_prescription_records"
CLINICAL_EVENT_PRESCRIPTION_RECORDS = "clinical_event_prescription_records"
CENTER_FOLLOW_UP_CATEGORIES_RN = "center_follow_up_categories"
PET_FOLLOW_UPS_RN = "pet_follow_ups"
CLINICAL_EVENT_FOLLOW_UPS_RN = "clinical_event_follow_ups"
PET_ACTIVITY_LOGS_RN = "pet_activity_logs"
CONTACT_ACTIVITY_LOGS_RN = "contact_activity_logs"
VET_ACTIVITY_LOGS_RN = "vet_activity_logs"
CENTER_SETTINGS_RN = "center_settings"
ALLOWED_SPECIES_CENTER_SETTINGS_RN = "allowed_species_center_settings"
CENTER_ACTIVITY_LOGS_RN = "center_activity_logs"
CONSULTATION_ACTIVITY_LOGS_RN = "consultation_activity_logs"
FOLLOW_UP_CATEGORY_ACTIVITY_LOGS_RN = "follow_up_category_activity_logs"
CENTER_CONSULTATION_TEMPLATES_RN = "center_consultation_templates"
CENTER_PROCEDURE_TEMPLATES_RN = "center_procedure_templates"
PROCEDURE_TYPE_TEMPLATES_RN = "procedure_type_templates"
DEFAULT_SOAP_TEMPLATE_CONSULTATION_TEMPLATES_RN = "default_soap_template_consultation_templates"
CONSULTATION_TYPE_CONSULTATION_TEMPLATES_RN = "consultation_type_consultation_templates"
CENTER_CLINICAL_FOCUS_FOR_SOAP_TEMPLATES_RN = "center_clinical_focus_for_soap_templates"
CENTER_SOAP_TEMPLATES_RN = "center_soap_templates"
SPECIES_SOAP_TEMPLATES_RN = "species_soap_templates"
CENTER_CLINICAL_EVENTS_RN = "center_clinical_events"
PET_CLINICAL_EVENTS_RN = "pet_clinical_events"
VET_CLINICAL_EVENTS_RN = "vet_clinical_events"
CONSULTATION_CLINICAL_EVENTS_RN = "consultation_clinical_events"
CLINICAL_EVENT_IMAGES_RN = "clinical_event_images"
IMAGE_CLINICAL_EVENT_IMAGES_RN = "image_clinical_event_images"
CENTER_CRITICAL_CASES_RN = "center_critical_cases"
PET_CRITICAL_CASES_RN = "pet_critical_cases"
DISEASE_CASE_CRITICAL_CASES_RN = "disease_case_critical_cases"
PROBLEM_CASE_CRITICAL_CASES_RN = "problem_case_critical_cases"
CONSULTATION_CRITICAL_CASES_RN = "consultation_critical_cases"
CREATED_BY_CRITICAL_CASES_RN = "created_by_critical_cases"
PET_HOSPITALIZATIONS_RN = "pet_hospitalizations"
CENTER_HOSPITALIZATIONS_RN = "center_hospitalizations"
CONSULTATION_HOSPITALIZATIONS_RN = "consultation_hospitalizations"
CREATED_BY_HOSPITALIZATIONS_RN = "created_by_hospitalizations"
DISCHARGED_BY_HOSPITALIZATIONS_RN = "discharged_by_hospitalizations"
CENTER_HOSPITALIZATION_UNITS_RN = "center_hospitalization_units"
CENTER_HOSPITALIZATION_UNIT_ASSIGNMENTS_RN = "center_hospitalization_unit_assigmnets"
HOSPITALIZATION_UNIT_ASSIGNMENTS_RN = "hospitalization_unit_assignments"
HOSPITALIZATION_UNIT_ASSIGMENTS_RN = "hospitalization_unit_units_assigments"
UNIT_HOSPITALIZATION_UNIT_ASSIGNMENTS_RN = "unit_hospitalization_unit_assignments"
HOSPITALIZATION_PET_DAILY_RECORDS_RN = "hospitalization_pet_daily_records"
CENTER_HOSPITALIZED_PET_DAILY_RECORDS_RN = "center_hospitalized_pet_daily_records"
CREATED_BY_HOSPITALIZED_PET_DAILY_RECORDS_RN = "created_by_hospitalized_pet_daily_records"
CENTER_CAMPAIGNS_RN = "center_campaigns"
CREATED_BY_CAMPAIGNS_RN = "created_by_campaigns"
CAMPAIGN_ACTIONS_RN = "campaign_actions"
CENTER_CAMPAIGN_ACTIONS_RN = "center_campaign_actions"
CAMPAIGN_TARGETS_RN = "campaign_targets"
CENTER_CAMPAIGN_TARGETS_RN = "center_campaign_targets"
CAMPAIGN_RESTRICTION_SETS_RN = "campaign_restriction_sets"
CENTER_CAMPAIGN_RESTRICTION_SETS_RN = "center_campaign_restriction_sets"
CREATED_BY_CAMPAIGN_RESTRICTION_SETS_RN = "created_by_campaign_restriction_sets"
CAMPAIGN_ENROLLMENTS_RN = "campaign_enrollments"
PET_CAMPAIGN_ENROLLMENTS_RN = "pet_campaign_enrollments"
CENTER_CAMPAIGN_ENROLLMENTS_RN = "center_campaign_enrollments"
CENTER_PRESCRIPTIONS_RN = "center_prescriptions"
PET_PRESCRIPTIONS_RN = "pet_prescriptions"
MEDICATION_PRESCRIPTIONS_RN = "medication_prescriptions"
CLINICAL_EVENT_PRESCRIPTIONS_RN = "clinical_event_prescriptions"
CENTER_FOLLOW_UPS_RN = "center_follow_ups"
CATEGORY_FOLLOW_UPS_RN = "category_follow_ups"
PET_CONTACTS_RN = "pet_contacts"
CONTACT_PET_CONTACTS_RN = "contact_pet_contacts"
CONTACT_FOLLOW_UPS_RN = "contact_follow_ups"
CENTER_APPOINTMENTS_RN = "center_appointments"
ASSIGNED_VET_APPOINTMENTS_RN = "assigned_vet_appointments"
PET_APPOINTMENTS_RN = "pet_appointments"

# UniqueConstraint names

UNIQUE_VET_CENTER_PERSONNEL_CENTER_COUNTRY_DNI = "unique_vet_center_personnel_center_country_dni"
UNIQUE_CONTACT_CENTER_COUNTRY_DNI = "unique_contact_center_country_dni"
UNIQUE_SPECIES_CENTER_NAME = "unique_species_center_name"
UNIQUE_BREED_SPECIES_NAME = "unique_breed_species_name"
UNIQUE_HISTORY_PET_CENTER = "unique_history_pet_center"
UNIQUE_DISEASE_GROUP_NAME_PER_CENTER = "unique_disease_group_name_per_center"
UNIQUE_DISEASE_GROUP_CODE_PER_CENTER = "unique_disease_group_code_per_center"
UNIQUE_DISEASE_NAME_SPECIES_CENTER = "unique_disease_name_species_center"
UNIQUE_DISEASE_CODE_PER_CENTER = "unique_disease_code_per_center"
UNIQUE_DISEASE_EVENT_PER_CASE_TYPE_DATETIME_CONSULTATION = "unique_disease_event_per_case_type_datetime_consultation"
UNIQUE_PROBLEM_GROUP_NAME_PER_CENTER = "unique_problem_group_name_per_center"
UNIQUE_PROBLEM_GROUP_CODE_PER_CENTER = "unique_problem_group_code_per_center"
UNIQUE_PROBLEM_PER_CENTER = "unique_problem_per_center"
UNIQUE_PROBLEM_CATALOG_CODE_PER_CENTER = "unique_problem_catalog_code_per_center"
UNIQUE_PROBLEM_CATALOG_NAME_PER_CENTER = "unique_problem_catalog_name_per_center"
UNIQUE_PROBLEM_CASE_PER_PET_PER_DATE = "unique_problem_case_per_pet_per_date"
UNIQUE_PROBLEM_CASE_PER_PET_PROBLEM_DATE_PER_CENTER = "unique_problem_case_per_pet_problem_date_per_center"
UNIQUE_PROBLEM_EVENT_PER_CASE_TYPE_DATE = "unique_problem_event_per_case_type_date"
UNIQUE_PROCEDURE_TYPE_CODE_PER_CENTER = "unique_procedure_type_code_per_center"
UNIQUE_PROCEDURE_TYPE_NAME_PER_CENTER = "unique_procedure_type_name_per_center"
UNIQUE_VACCINE_PER_SPECIES_CENTER = "unique_vaccine_per_species_center"
UNIQUE_VACCINE_CODE_PER_CENTER = "unique_vaccine_code_per_center"
UNIQUE_MEDICATION_CODE_PER_CENTER = "unique_medication_code_per_center"
UNIQUE_MEDICATION_PER_CENTER = "unique_medication_per_center"
UNIQUE_FOLLOW_UP_CATEGORY_CODE_PER_CENTER = "unique_follow_up_category_code_per_center"
UNIQUE_CONSULTATION_TEMPLATE_PER_CENTER = "unique_consultation_template_per_center"
UNIQUE_IMAGE_CLINICAL_EVENT_PAIR = "unique_image_clinical_event_pair"
UNIQUE_ACTIVE_CRITICAL_CASE_PER_DISEASE_CASE = "unique_active_critical_case_per_disease_case"
UNIQUE_ACTIVE_CRITICAL_CASE_PER_PROBLEM_CASE = "unique_active_critical_case_per_problem_case"
UNIQUE_ACTIVE_CRITICAL_CASE_PER_CONSULTATION = "unique_active_critical_case_per_consultation"
UNIQUE_ACTIVE_HOSPITALIZATION_PER_UNIT = "unique_active_hospitalization_per_pet"
UNIQUE_BED_CODE_PER_CENTER = "unique_bed_code_per_center"
UNIQUE_ACTIVE_ASSIGNMENT_PER_HOSPITALIZATION = "unique_active_assignment_per_hospitalization"
UNIQUE_ACTIVE_ASSIGNMENT_PER_UNIT = "unique_active_assignment_per_unit"
UNIQUE_DAILY_RECORD_PER_HOSPITALIZATION_DATETIME = "unique_daily_record_per_hospitalization_datetime"
UNIQUE_CAMPAIGN_CODE_PER_CENTER = "unique_campaign_code_per_center"
UNIQUE_CAMPAIGN_VACCINE_ACTION = "unique_campaign_vaccine_action"
UNIQUE_CAMPAIGN_PROCEDURE_ACTION = "unique_campaign_procedure_action"
UNIQUE_CAMPAIGN_CONSULTATION_ACTION = "unique_campaign_consultation_action"
UNIQUE_CAMPAIGN_TARGET_DEFINITION = "unique_campaign_target_definition"
UNIQUE_CAMPAIGN_RESTRICTION_SET_VERSION = "unique_campaign_restriction_set_version"
UNIQUE_ACTIVE_RESTRICTION_SET_PER_CAMPAIGN = "unique_active_restriction_set_per_campaign"
UNIQUE_CAMPAIGN_ENROLLMENTS = "unique_campaign_enrollment"
UNIQUE_COMORBIDITY_PER_PET = "unique_comorbidity_per_pet"
UNIQUE_FOLLOW_UP_PER_EVENT_CATEGORY_DATE = "unique_follow_up_per_event_category_date"
UNIQUE_PROCEDURE_TEMPLATE_PER_CENTER = "unique_procedure_template_per_center"

# Indexes

#123456789012345678901234567890
IDX_DISEASE_EVENT_CASE_TIMELINE = "idx_de_case_timeline"
IDX_DISEASE_EVENT_CENTER_TIMELINE = "idx_de_center_timeline"
IDX_DISEASE_EVENT_CONSULTATION = "idx_de_consult"
IDX_DISEASE_EVENT_TYPE = "idx_de_type"
IDX_DISEASE_EVENT_CASE_TYPE = "idx_de_case_type"

IDX_PROBLEM_GROUP_CENTER_ORDER = "idx_pg_center_order"
IDX_PROBLEM_GROUP_CENTER_ORDER_NAME = "idx_pg_center_ord_name"
IDX_PROBLEM_GROUP_CENTER_CODE = "idx_pg_center_code"
IDX_PROBLEM_GROUP_CENTER_NAME = "idx_pg_center_name"

IDX_PROBLEM_CATALOG_CENTER_CODE = "idx_pcat_center_code"
IDX_PROBLEM_CATALOG_CENTER_NAME = "idx_pcat_center_name"

IDX_PROBLEM_CASE_PET_STATUS = "idx_pcase_pet_status"
IDX_PROBLEM_CASE_CENTER_PET = "idx_pcase_center_pet"
IDX_PROBLEM_CASE_CATALOG = "idx_pcase_catalog"
IDX_PROBLEM_CASE_RELAPSE = "idx_pcase_relapse"
IDX_PROBLEM_CASE_PET_FIRST_NOTED = "idx_pcase_pet_first"

IDX_PROBLEM_EVENT_CASE_DATE_ID = "idx_pe_case_date"
IDX_PROBLEM_EVENT_CENTER_DATE = "idx_pe_center_date"

IDX_MEDICATION_CENTER = "idx_med_center"

IDX_PRESCRIPTION_CENTER_PET = "idx_rx_center_pet"
IDX_PRESCRIPTION_CENTER_MEDICATION = "idx_rx_center_med"
IDX_PRESCRIPTION_CLINICAL_EVENT = "idx_rx_ce"
IDX_PRESCRIPTION_STARTED_AT = "idx_rx_started"

IDX_FOLLOW_UP_CATEGORY_CENTER_LABEL = "idx_fuc_center_label"
IDX_FOLLOW_UP_CENTER_DONE_DUE_DATE = "idx_fu_center_due"
IDX_FOLLOW_UP_CENTER_PET_DONE = "idx_fu_center_pet"
IDX_FOLLOW_UP_CLINICAL_EVENT = "idx_fu_ce"

IDX_ACTIVITY_LOG_CENTER_PET_CREATED_AT = "idx_alog_center_pet"
IDX_ACTIVITY_LOG_CENTER_CONTACT_CREATED_AT = "idx_alog_center_contact"
IDX_ACTIVITY_LOG_CONSULTATION = "idx_alog_consult"
IDX_ACTIVITY_LOG_CATEGORY = "idx_alog_category"

IDX_CONSULTATION_TEMPLATE_CENTER_ACTIVE_NAME = "idx_ctpl_center_name"
IDX_CONSULTATION_TEMPLATE_TYPE = "idx_ctpl_type"

IDX_CLINICAL_EVENT_IMAGE_EVENT_ID = "idx_ceimg_event"

IDX_APPOINTMENT_CENTER_START = "idx_appt_center_start"
IDX_APPOINTMENT_VET_SCHEDULED_START = "idx_appt_vet_start"
IDX_APPOINTMENT_PET = "idx_appt_pet"

IDX_CRITICAL_STATUS = "idx_crit_status"
IDX_CRITICAL_PET_STATUS = "idx_crit_pet_status"
IDX_CRITICAL_CENTER_STATUS = "idx_crit_center_status"

IDX_HOSPITALIZATION_PET_STATUS = "idx_hosp_pet_status"
IDX_HOSPITALIZATION_CENTER_ADMITTED = "idx_hosp_center_admit"
IDX_HOSPITALIZATION_STATUS_CENTER = "idx_hosp_status_center"
IDX_ACTIVE_HOSPITALIZATION_PER_PET = "idx_hosp_active_pet"

IDX_HOSPITALIZATION_UNIT_CENTER_ACTIVE = "idx_hu_center_active"

IDX_DAILY_RECORD_HOSPITALIZATION_DATETIME = "idx_hdr_hosp_dt"
IDX_DAILY_RECORD_CENTER_DATETIME = "idx_hdr_center_dt"

IDX_CAMPAIGN_CENTER_ACTIVE = "idx_campaign_center"
IDX_CAMPAIGN_CENTER_START_DATE = "idx_campaign_start"

IDX_CAMPAIGN_ENROLLMENT_CENTER = "idx_cenr_center"
IDX_CAMPAIGN_ENROLLMENT_CAMPAIGN = "idx_cenr_campaign"
IDX_CAMPAIGN_ENROLLMENT_PET = "idx_cenr_pet"
IDX_CAMPAIGN_ENROLLMENT_STATUS = "idx_cenr_status"
IDX_CONSULTATION_TYPE_CENTER_LABEL = "idx_cons_type_center_label"
IDX_COSULTATION_TYPE_CENTER_CODE = "idx_cons_type_center_code"
IDX_PROCEDURE_TEMPLATE_CENTER_ACTIVE_NAME = "idx_proc_temp_ctr_active_name"
IDX_PROCEDURE_TEMPLATE_TYPE = "idx_proc_temp_type"
IDX_CLIONICAL_EVENT_CONSULTATION_APPLIED = "idx_clin_evt_cons_applie"
IDX_CLINICAL_EVENT_CONSULTATION_CLOSED = "idx_clin_evt_cons_closed"
IDX_CLINICAL_EVENT_PET_TIMELINE = "idx_clin_evt_pet_timelin"
IDX_CLINICAL_EVENT_CENTER_DATE = "idx_clin_evt_center_date"
IDX_UNIT_ASSIGMENT_CENTER_ACTIVE = "idx_unit_assig_ctr_active"
IDX_UNIT_ASSIGMENT_HOSPITALIZATION = "idx_unit_assig_hosp"

# Check Constraint

CRITICAL_CASE_SINGLE_ORIGIN = "critical_case_single_origin"
HOSPITALIZATION_DISCHARGED_REQUIRES_TIMESTAMP = "hospitalization_discharged_requires_timestamp"
HOSPITALIZATION_DISEASED_REQUIRES_TIMESTAMP = "hospitalization_deceased_requires_timestamp"
HOSPITALIZATION_ACTIVE_CANNOT_HAVE_DISCHARGED_AT = "hospitalization_active_cannot_have_discharged_at"
CAMPAIGN_VALID_DATE_RANGE = "campaign_valid_date_range"

# Regexes

INTERNATIONAL_PHONE_NUMBER_REGEX = r"^\+?[0-9\s\-\(\)]{7,20}$"